{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.foucaultleon",
    "module": "flterraforged-engine",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.foucaultleon",
          "module": "flterraforged-engine-api",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "flterraforged-engine-0.1.0-SNAPSHOT.jar",
          "url": "flterraforged-engine-0.1.0-SNAPSHOT.jar",
          "size": 145602,
          "sha512": "0dc199cd0362c089bfd2428b7c810f8453cbdaf444c0619cc5de177a62df168069d28c6a3df4ffc32479ea75d69f7271a3c70ad1b50175a05a5f436b41c07c0c",
          "sha256": "d3210b338de0871412b38a8598f6767d83bdc160d6f77c51ce264e6817b5dcb1",
          "sha1": "824ef61768a87c61cc22b1c936195ef338ef022a",
          "md5": "ea6f4eb3394e695e086a2441e3ed7cfc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.foucaultleon",
          "module": "flterraforged-engine-api",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "flterraforged-engine-0.1.0-SNAPSHOT.jar",
          "url": "flterraforged-engine-0.1.0-SNAPSHOT.jar",
          "size": 145602,
          "sha512": "0dc199cd0362c089bfd2428b7c810f8453cbdaf444c0619cc5de177a62df168069d28c6a3df4ffc32479ea75d69f7271a3c70ad1b50175a05a5f436b41c07c0c",
          "sha256": "d3210b338de0871412b38a8598f6767d83bdc160d6f77c51ce264e6817b5dcb1",
          "sha1": "824ef61768a87c61cc22b1c936195ef338ef022a",
          "md5": "ea6f4eb3394e695e086a2441e3ed7cfc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flterraforged-engine-0.1.0-SNAPSHOT-sources.jar",
          "url": "flterraforged-engine-0.1.0-SNAPSHOT-sources.jar",
          "size": 92884,
          "sha512": "21fc4cae42c8ca83537718c72079f7cffe2edf7ced40e4b77f8f48055ae1468d6eebc062d1b389bd92e4cf39d53942b6d77e6e33557cb365203136b3dcf10850",
          "sha256": "5970a9a9fe8cba20a4f101469a9bd90298c58e7e55022f37280183b769fecae3",
          "sha1": "c540c6c996526653130a8a92620a4fd511e90f50",
          "md5": "fef19b06ddead31322c9e202e707d631"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flterraforged-engine-0.1.0-SNAPSHOT-javadoc.jar",
          "url": "flterraforged-engine-0.1.0-SNAPSHOT-javadoc.jar",
          "size": 418424,
          "sha512": "8c19dc1b8e3d299d92ff8fd38141beb20b38fa84e6a33a1c7b426a5cb62d8e3af30535e3492c4e41a9b433b7e6ed74722e2880ab5866b1d0f6fcecf9c79b6096",
          "sha256": "fc8899818364b26e96142f608abd84b65c5842875b677f8c1778053a9e865e05",
          "sha1": "8edea26e350bb51df1d5a4462ec21e33ac7d3b79",
          "md5": "4abeb06eeb25641f0820d956f755a4ee"
        }
      ]
    }
  ]
}
