{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.foucaultleon",
    "module": "flterraforged-engine",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.foucaultleon",
          "module": "flterraforged-engine-api",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "flterraforged-engine-0.1.0-SNAPSHOT.jar",
          "url": "flterraforged-engine-0.1.0-SNAPSHOT.jar",
          "size": 140856,
          "sha512": "92d97e37c6261045ed8268c1e123196bfffc7f74862693c89cbd195f94f40dd863a0de58dba19c2c02d0e3fb816b915733c08e1b58512939b7ea48d0682103f4",
          "sha256": "bdd5191a75a35c91e76c399ab1d3bf165c36c837b209e35ab6d79515641263b8",
          "sha1": "f1afdfb1a0417cdedab61c12dd57bc26abf70bb7",
          "md5": "5badc7d4da0237adb25e5a15d575cbbf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.foucaultleon",
          "module": "flterraforged-engine-api",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "flterraforged-engine-0.1.0-SNAPSHOT.jar",
          "url": "flterraforged-engine-0.1.0-SNAPSHOT.jar",
          "size": 140856,
          "sha512": "92d97e37c6261045ed8268c1e123196bfffc7f74862693c89cbd195f94f40dd863a0de58dba19c2c02d0e3fb816b915733c08e1b58512939b7ea48d0682103f4",
          "sha256": "bdd5191a75a35c91e76c399ab1d3bf165c36c837b209e35ab6d79515641263b8",
          "sha1": "f1afdfb1a0417cdedab61c12dd57bc26abf70bb7",
          "md5": "5badc7d4da0237adb25e5a15d575cbbf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flterraforged-engine-0.1.0-SNAPSHOT-sources.jar",
          "url": "flterraforged-engine-0.1.0-SNAPSHOT-sources.jar",
          "size": 90547,
          "sha512": "22acbb34d108d81b14d0f32a05a791a390e9920859bc27c908a7dd66c47124d7f352fb2ef55e5dc51d7b9891cb99f09f3e720919669095598ce7438b3bcd7d30",
          "sha256": "53ca630c791a928e03b79c26c9e4d98738f81ba71f8d858cfff59be888486ff8",
          "sha1": "25f6dd458f04fa9aafbfa8e4697a34c6f6958b80",
          "md5": "f2ad623fb9b806ce34b51c4714ba4a11"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flterraforged-engine-0.1.0-SNAPSHOT-javadoc.jar",
          "url": "flterraforged-engine-0.1.0-SNAPSHOT-javadoc.jar",
          "size": 417724,
          "sha512": "5ba8e66d4f1ed469948d50999e3283623810b3a5bce29fb186be083e97836b86b9c9122938fb13db7457c5b6e4a6371f82de91e8009b78177400c9c868c4451b",
          "sha256": "8bfd24a33631e8aeef665fcf951089b6d02bc6973d7145f645d5dd2d2a1cbf1e",
          "sha1": "e14666b5749c8e1bc4e737521909502e4e66633c",
          "md5": "522c7b96773dedf69c724fdffa407ad8"
        }
      ]
    }
  ]
}
